package br.com.agrsystem.model.entities;
// Generated 02/01/2017 11:02:59 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Files generated by hbm2java
 */
@Entity
@Table(name="files"
    ,schema="public"
)
public class Files  implements java.io.Serializable {


     private long pk;
     private Instance instance;
     private String filepath;
     private String fileTsuid;
     private String fileMd5;
     private Long fileSize;
     private Integer fileStatus;
     private Date md5CheckTime;
     private Date createdTime;

    public Files() {
    }

	
    public Files(long pk, String filepath, String fileTsuid) {
        this.pk = pk;
        this.filepath = filepath;
        this.fileTsuid = fileTsuid;
    }
    public Files(long pk, Instance instance, String filepath, String fileTsuid, String fileMd5, Long fileSize, Integer fileStatus, Date md5CheckTime, Date createdTime) {
       this.pk = pk;
       this.instance = instance;
       this.filepath = filepath;
       this.fileTsuid = fileTsuid;
       this.fileMd5 = fileMd5;
       this.fileSize = fileSize;
       this.fileStatus = fileStatus;
       this.md5CheckTime = md5CheckTime;
       this.createdTime = createdTime;
    }
   
     @Id 

    
    @Column(name="pk", unique=true, nullable=false)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instance_fk")
    public Instance getInstance() {
        return this.instance;
    }
    
    public void setInstance(Instance instance) {
        this.instance = instance;
    }

    
    @Column(name="filepath", nullable=false)
    public String getFilepath() {
        return this.filepath;
    }
    
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    
    @Column(name="file_tsuid", nullable=false)
    public String getFileTsuid() {
        return this.fileTsuid;
    }
    
    public void setFileTsuid(String fileTsuid) {
        this.fileTsuid = fileTsuid;
    }

    
    @Column(name="file_md5")
    public String getFileMd5() {
        return this.fileMd5;
    }
    
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    
    @Column(name="file_size")
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    
    @Column(name="file_status")
    public Integer getFileStatus() {
        return this.fileStatus;
    }
    
    public void setFileStatus(Integer fileStatus) {
        this.fileStatus = fileStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="md5_check_time", length=29)
    public Date getMd5CheckTime() {
        return this.md5CheckTime;
    }
    
    public void setMd5CheckTime(Date md5CheckTime) {
        this.md5CheckTime = md5CheckTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", length=29)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


