package br.com.agrsystem.model.entities;
// Generated 02/01/2017 11:02:59 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Instance generated by hbm2java
 */
@Entity
@Table(name="instance"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="sop_iuid") 
)
public class Instance  implements java.io.Serializable {


     private long pk;
     private Series series;
     private String sopIuid;
     private String sopCuid;
     private String instNo;
     private Date contentDatetime;
     private String srComplete;
     private String srVerified;
     private String instCustom1;
     private String instCustom2;
     private String instCustom3;
     private String extRetrAet;
     private String retrieveAets;
     private int availability;
     private int instStatus;
     private boolean allAttrs;
     private boolean commitment;
     private boolean archived;
     private Date createdTime;
     private Date updatedTime;
     private byte[] instAttrs;

    public Instance() {
    }

	
    public Instance(long pk, String sopIuid, String sopCuid, int availability, int instStatus, boolean allAttrs, boolean commitment, boolean archived) {
        this.pk = pk;
        this.sopIuid = sopIuid;
        this.sopCuid = sopCuid;
        this.availability = availability;
        this.instStatus = instStatus;
        this.allAttrs = allAttrs;
        this.commitment = commitment;
        this.archived = archived;
    }
    public Instance(long pk, Series series, String sopIuid, String sopCuid, String instNo, Date contentDatetime, String srComplete, String srVerified, String instCustom1, String instCustom2, String instCustom3, String extRetrAet, String retrieveAets, int availability, int instStatus, boolean allAttrs, boolean commitment, boolean archived, Date createdTime, Date updatedTime, byte[] instAttrs) {
       this.pk = pk;
       this.series = series;
       this.sopIuid = sopIuid;
       this.sopCuid = sopCuid;
       this.instNo = instNo;
       this.contentDatetime = contentDatetime;
       this.srComplete = srComplete;
       this.srVerified = srVerified;
       this.instCustom1 = instCustom1;
       this.instCustom2 = instCustom2;
       this.instCustom3 = instCustom3;
       this.extRetrAet = extRetrAet;
       this.retrieveAets = retrieveAets;
       this.availability = availability;
       this.instStatus = instStatus;
       this.allAttrs = allAttrs;
       this.commitment = commitment;
       this.archived = archived;
       this.createdTime = createdTime;
       this.updatedTime = updatedTime;
       this.instAttrs = instAttrs;
    }
   
     @Id 

    
    @Column(name="pk", unique=true, nullable=false)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="series_fk")
    public Series getSeries() {
        return this.series;
    }
    
    public void setSeries(Series series) {
        this.series = series;
    }

    
    @Column(name="sop_iuid", unique=true, nullable=false)
    public String getSopIuid() {
        return this.sopIuid;
    }
    
    public void setSopIuid(String sopIuid) {
        this.sopIuid = sopIuid;
    }

    
    @Column(name="sop_cuid", nullable=false)
    public String getSopCuid() {
        return this.sopCuid;
    }
    
    public void setSopCuid(String sopCuid) {
        this.sopCuid = sopCuid;
    }

    
    @Column(name="inst_no")
    public String getInstNo() {
        return this.instNo;
    }
    
    public void setInstNo(String instNo) {
        this.instNo = instNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="content_datetime", length=29)
    public Date getContentDatetime() {
        return this.contentDatetime;
    }
    
    public void setContentDatetime(Date contentDatetime) {
        this.contentDatetime = contentDatetime;
    }

    
    @Column(name="sr_complete")
    public String getSrComplete() {
        return this.srComplete;
    }
    
    public void setSrComplete(String srComplete) {
        this.srComplete = srComplete;
    }

    
    @Column(name="sr_verified")
    public String getSrVerified() {
        return this.srVerified;
    }
    
    public void setSrVerified(String srVerified) {
        this.srVerified = srVerified;
    }

    
    @Column(name="inst_custom1")
    public String getInstCustom1() {
        return this.instCustom1;
    }
    
    public void setInstCustom1(String instCustom1) {
        this.instCustom1 = instCustom1;
    }

    
    @Column(name="inst_custom2")
    public String getInstCustom2() {
        return this.instCustom2;
    }
    
    public void setInstCustom2(String instCustom2) {
        this.instCustom2 = instCustom2;
    }

    
    @Column(name="inst_custom3")
    public String getInstCustom3() {
        return this.instCustom3;
    }
    
    public void setInstCustom3(String instCustom3) {
        this.instCustom3 = instCustom3;
    }

    
    @Column(name="ext_retr_aet")
    public String getExtRetrAet() {
        return this.extRetrAet;
    }
    
    public void setExtRetrAet(String extRetrAet) {
        this.extRetrAet = extRetrAet;
    }

    
    @Column(name="retrieve_aets")
    public String getRetrieveAets() {
        return this.retrieveAets;
    }
    
    public void setRetrieveAets(String retrieveAets) {
        this.retrieveAets = retrieveAets;
    }

    
    @Column(name="availability", nullable=false)
    public int getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(int availability) {
        this.availability = availability;
    }

    
    @Column(name="inst_status", nullable=false)
    public int getInstStatus() {
        return this.instStatus;
    }
    
    public void setInstStatus(int instStatus) {
        this.instStatus = instStatus;
    }

    
    @Column(name="all_attrs", nullable=false)
    public boolean isAllAttrs() {
        return this.allAttrs;
    }
    
    public void setAllAttrs(boolean allAttrs) {
        this.allAttrs = allAttrs;
    }

    
    @Column(name="commitment", nullable=false)
    public boolean isCommitment() {
        return this.commitment;
    }
    
    public void setCommitment(boolean commitment) {
        this.commitment = commitment;
    }

    
    @Column(name="archived", nullable=false)
    public boolean isArchived() {
        return this.archived;
    }
    
    public void setArchived(boolean archived) {
        this.archived = archived;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", length=29)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", length=29)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    
    @Column(name="inst_attrs")
    public byte[] getInstAttrs() {
        return this.instAttrs;
    }
    
    public void setInstAttrs(byte[] instAttrs) {
        this.instAttrs = instAttrs;
    }

}


