package br.com.agrsystem.model.entities;
// Generated 02/01/2017 13:42:07 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,schema="public"
)
public class Roles  implements java.io.Serializable {


     private int cod;
     private Users users;
     private String roles;

    public Roles() {
    }

	
    public Roles(int cod) {
        this.cod = cod;
    }
    public Roles(int cod, Users users, String roles) {
       this.cod = cod;
       this.users = users;
       this.roles = roles;
    }
   
     @Id 

    
    @Column(name="cod", unique=true, nullable=false)
    public int getCod() {
        return this.cod;
    }
    
    public void setCod(int cod) {
        this.cod = cod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="roles")
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }




}


