package br.com.agrsystem.model.entities;
// Generated 02/01/2017 11:02:59 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StatusLaudo generated by hbm2java
 */
@Entity
@Table(name="status_laudo"
    ,schema="public"
)
public class StatusLaudo  implements java.io.Serializable {


     private int codigo;
     private String descricao;

    public StatusLaudo() {
    }

	
    public StatusLaudo(int codigo) {
        this.codigo = codigo;
    }
    public StatusLaudo(int codigo, String descricao) {
       this.codigo = codigo;
       this.descricao = descricao;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="descricao", length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


