package br.com.agrsystem.model.entities;
// Generated 02/01/2017 11:02:59 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Study generated by hbm2java
 */
@Entity
@Table(name="study")
public class Study  implements java.io.Serializable {


     private long pk;
     private Patient patient;
     private String studyIuid;
     private String studyId;
     private Date studyDatetime;
     private String accessionNo;
     private String refPhysician;
     private String refPhysFnSx;
     private String refPhysGnSx;
     private String refPhysIName;
     private String refPhysPName;
     private String studyDesc;
     private String studyCustom1;
     private String studyCustom2;
     private String studyCustom3;
     private String studyStatusId;
     private String modsInStudy;
     private String cuidsInStudy;
     private int numSeries;
     private int numInstances;
     private String extRetrAet;
     private String retrieveAets;
     private String filesetIuid;
     private String filesetId;
     private int availability;
     private int studyStatus;
     private Date checkedTime;
     private Date createdTime;
     private Date updatedTime;
     private byte[] studyAttrs;

    public Study() {
    }

	
    public Study(long pk, String studyIuid, int numSeries, int numInstances, int availability, int studyStatus) {
        this.pk = pk;
        this.studyIuid = studyIuid;
        this.numSeries = numSeries;
        this.numInstances = numInstances;
        this.availability = availability;
        this.studyStatus = studyStatus;
    }
    public Study(long pk, Patient patient, String studyIuid, String studyId, Date studyDatetime, String accessionNo, String refPhysician, String refPhysFnSx, String refPhysGnSx, String refPhysIName, String refPhysPName, String studyDesc, String studyCustom1, String studyCustom2, String studyCustom3, String studyStatusId, String modsInStudy, String cuidsInStudy, int numSeries, int numInstances, String extRetrAet, String retrieveAets, String filesetIuid, String filesetId, int availability, int studyStatus, Date checkedTime, Date createdTime, Date updatedTime, byte[] studyAttrs) {
       this.pk = pk;
       this.patient = patient;
       this.studyIuid = studyIuid;
       this.studyId = studyId;
       this.studyDatetime = studyDatetime;
       this.accessionNo = accessionNo;
       this.refPhysician = refPhysician;
       this.refPhysFnSx = refPhysFnSx;
       this.refPhysGnSx = refPhysGnSx;
       this.refPhysIName = refPhysIName;
       this.refPhysPName = refPhysPName;
       this.studyDesc = studyDesc;
       this.studyCustom1 = studyCustom1;
       this.studyCustom2 = studyCustom2;
       this.studyCustom3 = studyCustom3;
       this.studyStatusId = studyStatusId;
       this.modsInStudy = modsInStudy;
       this.cuidsInStudy = cuidsInStudy;
       this.numSeries = numSeries;
       this.numInstances = numInstances;
       this.extRetrAet = extRetrAet;
       this.retrieveAets = retrieveAets;
       this.filesetIuid = filesetIuid;
       this.filesetId = filesetId;
       this.availability = availability;
       this.studyStatus = studyStatus;
       this.checkedTime = checkedTime;
       this.createdTime = createdTime;
       this.updatedTime = updatedTime;
       this.studyAttrs = studyAttrs;
    }
   
     @Id 

    
    @Column(name="pk", unique=true, nullable=false)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_fk")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    @Column(name="study_iuid", unique=true, nullable=false)
    public String getStudyIuid() {
        return this.studyIuid;
    }
    
    public void setStudyIuid(String studyIuid) {
        this.studyIuid = studyIuid;
    }

    
    @Column(name="study_id")
    public String getStudyId() {
        return this.studyId;
    }
    
    public void setStudyId(String studyId) {
        this.studyId = studyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="study_datetime", length=29)
    public Date getStudyDatetime() {
        return this.studyDatetime;
    }
    
    public void setStudyDatetime(Date studyDatetime) {
        this.studyDatetime = studyDatetime;
    }

    
    @Column(name="accession_no")
    public String getAccessionNo() {
        return this.accessionNo;
    }
    
    public void setAccessionNo(String accessionNo) {
        this.accessionNo = accessionNo;
    }

    
    @Column(name="ref_physician")
    public String getRefPhysician() {
        return this.refPhysician;
    }
    
    public void setRefPhysician(String refPhysician) {
        this.refPhysician = refPhysician;
    }

    
    @Column(name="ref_phys_fn_sx")
    public String getRefPhysFnSx() {
        return this.refPhysFnSx;
    }
    
    public void setRefPhysFnSx(String refPhysFnSx) {
        this.refPhysFnSx = refPhysFnSx;
    }

    
    @Column(name="ref_phys_gn_sx")
    public String getRefPhysGnSx() {
        return this.refPhysGnSx;
    }
    
    public void setRefPhysGnSx(String refPhysGnSx) {
        this.refPhysGnSx = refPhysGnSx;
    }

    
    @Column(name="ref_phys_i_name")
    public String getRefPhysIName() {
        return this.refPhysIName;
    }
    
    public void setRefPhysIName(String refPhysIName) {
        this.refPhysIName = refPhysIName;
    }

    
    @Column(name="ref_phys_p_name")
    public String getRefPhysPName() {
        return this.refPhysPName;
    }
    
    public void setRefPhysPName(String refPhysPName) {
        this.refPhysPName = refPhysPName;
    }

    
    @Column(name="study_desc")
    public String getStudyDesc() {
        return this.studyDesc;
    }
    
    public void setStudyDesc(String studyDesc) {
        this.studyDesc = studyDesc;
    }

    
    @Column(name="study_custom1")
    public String getStudyCustom1() {
        return this.studyCustom1;
    }
    
    public void setStudyCustom1(String studyCustom1) {
        this.studyCustom1 = studyCustom1;
    }

    
    @Column(name="study_custom2")
    public String getStudyCustom2() {
        return this.studyCustom2;
    }
    
    public void setStudyCustom2(String studyCustom2) {
        this.studyCustom2 = studyCustom2;
    }

    
    @Column(name="study_custom3")
    public String getStudyCustom3() {
        return this.studyCustom3;
    }
    
    public void setStudyCustom3(String studyCustom3) {
        this.studyCustom3 = studyCustom3;
    }

    
    @Column(name="study_status_id")
    public String getStudyStatusId() {
        return this.studyStatusId;
    }
    
    public void setStudyStatusId(String studyStatusId) {
        this.studyStatusId = studyStatusId;
    }

    
    @Column(name="mods_in_study")
    public String getModsInStudy() {
        return this.modsInStudy;
    }
    
    public void setModsInStudy(String modsInStudy) {
        this.modsInStudy = modsInStudy;
    }

    
    @Column(name="cuids_in_study")
    public String getCuidsInStudy() {
        return this.cuidsInStudy;
    }
    
    public void setCuidsInStudy(String cuidsInStudy) {
        this.cuidsInStudy = cuidsInStudy;
    }

    
    @Column(name="num_series", nullable=false)
    public int getNumSeries() {
        return this.numSeries;
    }
    
    public void setNumSeries(int numSeries) {
        this.numSeries = numSeries;
    }

    
    @Column(name="num_instances", nullable=false)
    public int getNumInstances() {
        return this.numInstances;
    }
    
    public void setNumInstances(int numInstances) {
        this.numInstances = numInstances;
    }

    
    @Column(name="ext_retr_aet")
    public String getExtRetrAet() {
        return this.extRetrAet;
    }
    
    public void setExtRetrAet(String extRetrAet) {
        this.extRetrAet = extRetrAet;
    }

    
    @Column(name="retrieve_aets")
    public String getRetrieveAets() {
        return this.retrieveAets;
    }
    
    public void setRetrieveAets(String retrieveAets) {
        this.retrieveAets = retrieveAets;
    }

    
    @Column(name="fileset_iuid")
    public String getFilesetIuid() {
        return this.filesetIuid;
    }
    
    public void setFilesetIuid(String filesetIuid) {
        this.filesetIuid = filesetIuid;
    }

    
    @Column(name="fileset_id")
    public String getFilesetId() {
        return this.filesetId;
    }
    
    public void setFilesetId(String filesetId) {
        this.filesetId = filesetId;
    }

    
    @Column(name="availability", nullable=false)
    public int getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(int availability) {
        this.availability = availability;
    }

    
    @Column(name="study_status", nullable=false)
    public int getStudyStatus() {
        return this.studyStatus;
    }
    
    public void setStudyStatus(int studyStatus) {
        this.studyStatus = studyStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="checked_time", length=29)
    public Date getCheckedTime() {
        return this.checkedTime;
    }
    
    public void setCheckedTime(Date checkedTime) {
        this.checkedTime = checkedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", length=29)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", length=29)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    
    @Column(name="study_attrs")
    public byte[] getStudyAttrs() {
        return this.studyAttrs;
    }
    
    public void setStudyAttrs(byte[] studyAttrs) {
        this.studyAttrs = studyAttrs;
    }
}


